#84 add template field
SnowdogApps/magento2-menu pull request #102
Opened 2020-03-30 11:19 UTC by kiber

DEV-65549

2020-09-16 10:44 UTC, akai-z requested changes
TODO: Fix merge conflicts in the following files:
[`view/adminhtml/web/vue/app.vue`](https://github.com/SnowdogApps/magento2-menu/blob/22430966771a685e5e4361523e69c31982a254c0/view/adminhtml/web/vue/app.vue)
[`view/adminhtml/web/vue/menu-type.vue`](https://github.com/SnowdogApps/magento2-menu/blob/22430966771a685e5e4361523e69c31982a254c0/view/adminhtml/web/vue/menu-type.vue)
[`view/adminhtml/web/vue/field-type/autocomplete.vue`](https://github.com/SnowdogApps/magento2-menu/blob/22430966771a685e5e4361523e69c31982a254c0/view/adminhtml/web/vue/field-type/autocomplete.vue)

2020-10-01 12:13 UTC, akai-z approved these changes

2020-10-05 06:58 UTC, jochhop approved these changes

2020-10-07 16:56 UTC, KamilBalwierz approved these changes

2020-10-28 09:14 UTC, akai-z requested changes
TODO: Fix [develop branch merge](https://github.com/SnowdogApps/magento2-menu/pull/102/commits/1d9233e5afe3ca6b1e3daf4c9a7bfbcf10b0fd4a) conflicts in the following files:
[`view/adminhtml/templates/menu/nodes.phtml`](https://github.com/SnowdogApps/magento2-menu/pull/102/commits/1d9233e5afe3ca6b1e3daf4c9a7bfbcf10b0fd4a#diff-9f49d9df8801512b198d845841fc4add2a48a2b43c4c5c3858eb67847466b900)
[`view/adminhtml/web/vue/field-type/checkbox.vue`](https://github.com/SnowdogApps/magento2-menu/pull/102/commits/1d9233e5afe3ca6b1e3daf4c9a7bfbcf10b0fd4a#diff-935df278827c55ea4671982ce7d62a9b4e14e846498c3a02eb0006ad5b2f9bb1)

2020-10-29 12:53 UTC, akai-z approved these changes

2020-10-30 09:54 UTC, jochhop approved these changes

2020-10-30 09:54 UTC, merged