[71279] Fix a menu save issue that prevents deleting all nodes of a menu
SnowdogApps/magento2-menu pull request #133
Opened 2020-09-25 19:35 UTC by akai-z

2020-09-28 05:46 UTC, jochhop requested changes

2020-09-28 05:46 UTC, jochhop commented on Controller/Adminhtml/Menu/Save.php
> +        $filterBuilder = $this->filterBuilderFactory->create();
Could you please extract all this get node collection logic into a separated private method?

2020-09-28 05:46 UTC, jochhop commented on Controller/Adminhtml/Menu/Save.php
> +        foreach ($existingNodes as $nodeId => $noe) {
Please fix the typo: `$noe`, it should be `$node`

2020-09-28 20:57 UTC, KamilBalwierz requested changes

2020-09-28 20:57 UTC, KamilBalwierz commented on Controller/Adminhtml/Menu/Save.php
> +            if (in_array($nodeId, array_keys($existingNodes))) {
`if(isset($existingNodes[$nodeId]))` seems to be more performant way to do this check

2020-09-30 13:10 UTC, KamilBalwierz approved these changes

2020-10-01 05:52 UTC, jochhop approved these changes

2020-10-29 11:39 UTC, jochhop approved these changes

2020-10-29 11:40 UTC, merged